//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaBizagi.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoanReq_FeriaDigitalEntities : DbContext
    {
        public LoanReq_FeriaDigitalEntities()
            : base("name=LoanReq_FeriaDigitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FuenteIngreso> FuenteIngresoes { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<TasasConfig> TasasConfigs { get; set; }
        public virtual DbSet<TGEN_CONDICION> TGEN_CONDICION { get; set; }
        public virtual DbSet<TGEN_DESCTABLA7> TGEN_DESCTABLA7 { get; set; }
        public virtual DbSet<TGEN_MARCA> TGEN_MARCA { get; set; }
        public virtual DbSet<TGEN_MODELO> TGEN_MODELO { get; set; }
        public virtual DbSet<TGEN_TIPOVIVIENDA> TGEN_TIPOVIVIENDA { get; set; }
    }
}
