//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaBizagi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuenteIngreso
    {
        public long idFuenteIngreso { get; set; }
        public int finalEnt { get; set; }
        public System.Guid guidFuenteIngreso { get; set; }
        public bool dsblFuenteIngreso { get; set; }
        public byte dplyFuenteIngreso { get; set; }
        public string Description { get; set; }
    }
}
