//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaBizagi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        public long PeriodId { get; set; }
        public int finalEnt { get; set; }
        public System.Guid guidPeriod { get; set; }
        public bool dsblPeriod { get; set; }
        public byte dplyPeriod { get; set; }
        public string Description { get; set; }
        public string EnumName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
