//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaBizagi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasasConfig
    {
        public long idTasasConfig { get; set; }
        public int finalEnt { get; set; }
        public System.Guid guidTasasConfig { get; set; }
        public bool dsblTasasConfig { get; set; }
        public byte dplyTasasConfig { get; set; }
        public Nullable<int> FromVehicleYear { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<int> PlazoMaximo { get; set; }
        public Nullable<double> Tasa { get; set; }
        public Nullable<int> UntilVehicleYear { get; set; }
        public string Description { get; set; }
    }
}
