//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaBizagi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGEN_DESCTABLA7
    {
        public int finalEnt { get; set; }
        public byte DES_CODTAB { get; set; }
        public short DES_CODIGO { get; set; }
        public string DES_DESCRIPCION { get; set; }
        public string CODEISO { get; set; }
        public string DES_STATUS { get; set; }
        public Nullable<int> DES_TUCodigo { get; set; }
    }
}
