//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaBizagi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGEN_CONDICION
    {
        public long idTGEN_CONDICION { get; set; }
        public int finalEnt { get; set; }
        public System.Guid guidTGEN_CONDICION { get; set; }
        public bool dsblTGEN_CONDICION { get; set; }
        public byte dplyTGEN_CONDICION { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
